version: '3'

services:
  db:
    build: 
      context: ./mongo
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # 默认开启授权，并创建超管用户 mongo -u godis -p godis@admin --authenticationDatabase admin
      - MONGO_INITDB_ROOT_PASSWORD=admin # 超管密码，敏感数据也可以使用 `secrets`，不赘述。
      - MONGO_INITDB_DATABASE=mock-platform # *.js 中默认的数据库
      - MONGO_INITDB_USERNAME=databaseroot
      - MONGO_INITDB_PASSWORD=databaseroot
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro #执行数据库初始化脚本
      - ./mongo-volume:/data/db # 挂载
    ports:
      - "27018:27017"
    restart: always
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      # - NODE_ENV=production
      - docker_db=db
    command: /bin/sh -c "npm install -s && npm install typescript tsc-alias -g && npm run init-db &&  npm run docker-deploy"
    ports:
      - "3888:3888"

    
